title: Carlos Dario Castaneda Mendoza.  # You can add your name here

#logo: 1.png # Use a relative path to logo image 

description: Senior Java Software Engineer. # Fix hyphenation 

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: dario20049@gmail.com # Allow visitors to contact you
