title: Carlos Dario Castaneda Mendoza. 
description: Sr Java Programmer.
show_downloads: false # Fix spelling
theme: jekyll-theme-minimal 
plugins:
  - jekyll-seo-tag # Add SEO plugin

# Personal info
name: Carlos Dario Castaneda Mendoza.
email: dario20049@gmail.com
# email_title: Email (Email title override)
phone: 52 5585324557
# phone_title: Phone (Phone title override)
website: https://dariocm.github.io/resumeCV/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

sass:
  sass_dir: _sass
  style: compressed

author:
  name: Carlos Dario Castaneda Mendoza
  email: dario20049@gmail.com
  phone: 52 5585324557
