title: Resume – Carlos Dario Castaneda Mendoza
description: Full-Stack Java Engineer | Spring Boot & React | Microservices | Cloud          
show_downloads: false # Fix spelling
theme: jekyll-theme-minimal 
plugins:
  - jekyll-seo-tag # Add SEO plugin
logo: DSCF7973.JPG

# Personal info
name: Carlos Dario Castaneda Mendoza.
email: dario20049@gmail.com
# email_title: Email (Email title override)
phone: 52 5585324557
# phone_title: Phone (Phone title override)
website: https://dariocm.github.io/resumeCV/
# website_title: Web (Website title override)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

sass:
  sass_dir: _sass
  style: compressed

author:
  name: Carlos Dario Castaneda Mendoza
  email: dario20049@gmail.com
  phone: 52 5585324557
  social:
    email:    dario20049@gmail.com
    rss:      https://simpled2ev.github.io/feed.xml # make sure you provide an absolute URL
    download: https://github.com/qwtel/hydejack/archive/v8.1.1.zip

hydejack:
  dark_mode:
    dynamic: true
    sunrise: 6
    sunset:  18
    icon:    true
    always:  false

enable_darkmode: true # enables switching between light/dark modes
enable_navbar_social: true # enables displaying social links in the navbar on the about page

footer:
  text: "&copy; 2024 Carlos Dario Castaneda Mendoza. Find me on: <a href='https://www.linkedin.com/in/carlos-dario-castaneda-mendoza/'>LinkedIn</a> | <a href='https://github.com/DarioCM'>GitHub</a>"
